glosario = {
    "Años de vida perdidos (AVP)": "Medida del impacto de una enfermedad al estimar los años no vividos debido a una muerte prematura.",
    "Azar": "Factor impredecible que puede afectar los resultados de un estudio; se controla con tamaño de muestra y aleatorización.",
    "Bias (Sesgo)": "Error sistemático en el diseño o ejecución del estudio que afecta la validez de los resultados.",
    "Brotes": "Aumento inusual de casos de una enfermedad en un lugar y tiempo determinados.",
    "Cohorte": "Grupo de personas seguidas a lo largo del tiempo para estudiar una exposición y su relación con un desenlace.",
    "Confusión": "Distorsión del efecto de la exposición por la influencia de una tercera variable relacionada con exposición y desenlace.",
    "Diseño transversal": "Estudio que mide exposición y desenlace al mismo tiempo.",
    "Distribución": "Descripción de cómo se presenta una enfermedad según persona, tiempo y lugar.",
    "Epidemia": "Incremento inesperado de casos de una enfermedad en una población específica.",
    "Epidemiología": "Ciencia que estudia la frecuencia, distribución y determinantes de enfermedades en poblaciones humanas.",
    "Frecuencia": "Número de veces que ocurre un evento (casos, muertes) en una población.",
    "Factores de riesgo": "Características o exposiciones que aumentan la probabilidad de desarrollar una enfermedad.",
    "Grupos de comparación": "Conjuntos de personas con y sin exposición para evaluar diferencias en desenlaces.",
    "Hipótesis": "Suposición que se pone a prueba en una investigación científica.",
    "Historia natural de la enfermedad": "Proceso natural que sigue una enfermedad desde su inicio hasta su resolución sin intervención.",
    "Incidencia": "Número de casos nuevos de una enfermedad en una población en riesgo durante un período de tiempo.",
    "Intervalo de confianza (IC)": "Rango de valores dentro del cual se espera que esté el valor verdadero con cierta probabilidad (usualmente 95%).",
    "Letalidad": "Proporción de personas con una enfermedad que mueren a causa de ella.",
    "Longitudinal": "Tipo de estudio que sigue a los individuos a través del tiempo.",
    "Mortalidad": "Número de muertes en una población durante un período específico.",
    "Muestreo": "Procedimiento para seleccionar participantes de una población de estudio.",
    "NNT (Número necesario a tratar)": "Número de personas que necesitan recibir una intervención para evitar un evento adverso.",
    "Notificación obligatoria": "Reporte obligatorio de enfermedades seleccionadas a las autoridades sanitarias.",
    "Odds ratio (OR)": "Medida de asociación utilizada principalmente en estudios de casos y controles.",
    "Observacional": "Diseño de estudio donde no se manipulan las exposiciones, solo se observan.",
    "Prevalencia": "Proporción de personas con una enfermedad en un momento o período determinado.",
    "Prueba diagnóstica": "Herramienta para detectar una enfermedad; se evalúa por sensibilidad, especificidad y valores predictivos.",
    "Quimioprofilaxis": "Uso de medicamentos para prevenir una enfermedad infecciosa antes de la exposición o en exposición reciente.",
    "Riesgo relativo (RR)": "Razón del riesgo de enfermedad entre los expuestos comparado con los no expuestos.",
    "Razón de tasas": "Comparación entre dos tasas de incidencia.",
    "Sensibilidad": "Capacidad de una prueba para detectar verdaderos positivos.",
    "Sesgo de selección": "Error al elegir la muestra que distorsiona la relación entre exposición y desenlace.",
    "Tasa de ataque": "Medida usada en brotes; casos nuevos en población expuesta durante un corto período.",
    "Tasa bruta": "Número de eventos (casos, muertes) por población total sin ajustar.",
    "Unidad de análisis": "Elemento sobre el que se hacen las observaciones (persona, comunidad, país).",
    "Utilidad diagnóstica": "Medida de cuán útil es una prueba para cambiar decisiones clínicas.",
    "Validez interna": "Grado en que los resultados del estudio reflejan la verdad para los participantes incluidos.",
    "Valor predictivo positivo (VPP)": "Proporción de verdaderos positivos entre los resultados positivos de una prueba.",
    "WHO (OMS)": "Organización Mundial de la Salud; autoridad internacional en salud pública.",
    "Xenopatogenia": "Introducción de patógenos desde otras especies (poco común pero interesante para zoonosis).",
    "Years Lived with Disability (YLD)": "Años vividos con enfermedad o discapacidad, parte del AVAD (DALY).",
    "Zoonosis": "Enfermedades que se transmiten de animales a humanos."
}
