# Tu clave de Gemini
GEMINI_API_KEY = "AIzaSyACVJM2zX4lUXtU-x4Zj8M9yDnbchbNTJ8"

# Las credenciales de Streamlit Authenticator
[credentials]

  [credentials.usernames]

    [credentials.usernames.test_user]
    email = "test@example.com"
    name = "Test User"
    password = "$2b$12$sI/pz3NlWRIfsu0iFV7tsOxX1SqyUwdBysQMJmZAZAZPLsUuUoacu"

    [credentials.usernames.admin]
    email = "admin@example.com"
    name = "Admin User"
    password = "$2b$12$sI/pz3NlWRIfsu0iFV7tsOxX1SqyUwdBysQMJmZAZAZPLsUuUoacu"

# Tu configuración de cookie
[cookie]
name = "my_app_cookie"
key = "a_very_long_and_random_string"
expiry_days = 30
